### ISSUE TITLE
Error: Library "ppx_mina" not found.

### ISSUE THREAD

**Issue by youtpout** [MartinOndejka/snarkyml_vs_o1js#1]
Hello,

I'm a newbie wit ocaml and I try to launch ocaml smartcontract  with dune but I got this error :

File "dune", line 64, characters 2-17:
64 |   zkapps_examples)
       ^^^^^^^^^^^^^^^
Error: Library "zkapps_examples" not found.
-> required by _build/default/run.exe
File "dune", line 68, characters 18-26:    
68 |   (pps ppx_snarky ppx_mina ppx_version ppx_jane ppx_compare h_list.ppx))
                       ^^^^^^^^
Error: Library "ppx_mina" not found.
-> required by _build/default/.merlin-conf/exe-run
-> required by _build/default/run.exe

What I need to do to install missing dependencies

**Comment by MartinOndejka** [comment]
https://github.com/MartinOndejka/snarkyml_vs_o1js/commit/313de05bac00c9c8aa440eb069c446e20b5ffbc3
